module.exports = {
  collectCoverageFrom: ['**/*.{ts,tsx}', '!**/node_modules/**', '!**/tests/**', '!**/src/environment/**', '!vite-env.d.ts'],
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['/node_modules/'],
  coverageThreshold: {
    global: {
      branches: 40,
      functions: 40,
      lines: 40,
      statements: 40,
    },
  },
  rootDir: './',
  setupFilesAfterEnv: ['<rootDir>/config/tests/setup.ts'],
  testEnvironment: 'jest-environment-jsdom',
  testEnvironmentOptions: {
    url: 'http://localhost',
  },
  moduleDirectories: ['<rootDir>src', 'node_modules'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'cjs', 'json'],
  roots: ['<rootDir>/src'],
  testPathIgnorePatterns: ['/node_modules/', 'coverage', 'build'],
  transformIgnorePatterns: ['/node_modules/', '<rootDir>/node_modules/'],
  moduleNameMapper: {
    '^axios$': require.resolve('axios'),
    '^.+\\.module\\.(css|less)$': 'identity-obj-proxy',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|wav|mp3|m4a|aac|oga)$': '<rootDir>/src/__mocks__/fileMock.js',
    '@root/(.*)': '<rootDir>/$1',
    '@config/(.*)': '<rootDir>/config/$1',
    '@pages/(.*)': '<rootDir>/src/pages/$1',
    '@components/(.*)': '<rootDir>/src/components/$1',
    '@containers/(.*)': '<rootDir>/src/containers/$1',
    '@services/(.*)': '<rootDir>/src/services/$1',
    '@interfaces/(.*)': '<rootDir>/src/interfaces/$1',
    '@contexts/(.*)': '<rootDir>/src/contexts/$1',
    '@utils/(.*)': '<rootDir>/src/utils/$1',
    '@environment/(.*)': '<rootDir>/src/environment/$1',
  },
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
};
