#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# This convention is to include reference of commit in jira task

echo "Checking commit message format"
message="$(cat $1)"
if [[ $message != "["*"-"*"]"* ]]
then
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "[<jira ref>-<jira id>] <message>"
  echo "-"
  echo "Example:"
  echo "[WEB-123] Add pipeline file"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
else
  echo "✅  The commit have correct format"
fi
